# Generated by Django 3.1.1 on 2020-09-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200909_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='fire_date',
            field=models.DateField(default=None, verbose_name='Дата увольнения'),
        ),
    ]
