# Generated by Django 3.1.1 on 2020-09-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20200909_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='fire_date',
            field=models.DateField(verbose_name='Дата увольнения'),
        ),
    ]
