# Generated by Django 3.1.1 on 2020-09-09 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20200909_1353'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='Occupation',
        ),
    ]
